import builtins


class C:
    # fmt: off
    FILENAME = "version.h"

    HEADER = ""\
        "#ifndef VERSION_H_\n"\
        "#define VERSION_H_\n"\
        "\n"\
        "/*\n"\
        "* This file has been generated by Subrepo python tool:\n"\
        "* https://github.com/DavidRbrt/subrepo\n"\
        "*/\n"\
        "\n"

    FOOTER = ""\
        "\n"\
        "#endif\n"
    # fmt: on

    def generate_line(variable, value):
        match type(value):
            case builtins.str:
                return f'#define {variable} "{value}"\n'
            case builtins.bool:
                if value == True:
                    str_value = "true"
                else:
                    str_value = "false"
                return f"#define {variable} {str_value}\n"
            case _:
                return f'#define {variable} "{value}"\n'


class Python:
    # fmt: off
    FILENAME = "version.py"

    HEADER = ""\
        '"""\n'\
        "This file has been generated by Subrepo python tool:\n"\
        "https://github.com/DavidRbrt/subrepo\n"\
        '"""\n'\
        "\n"\
        "class Version:\n"\

    FOOTER = ""
    # fmt: on

    def generate_line(variable, value):
        match type(value):
            case builtins.str:
                return f'    {variable} = "{value}"\n'
            case builtins.bool:
                return f"    {variable} = {value}\n"
            case _:
                return f'    {variable} = "{value}"\n'


def get_version_generator(language):
    match language:
        case "c":
            return C
        case "py":
            return Python
        case _:
            return None
