class C:
    # fmt: off
    FILENAME = "version.h"

    HEADER = ""\
        "#ifndef VERSION_H_\n"\
        "#define VERSION_H_\n"\
        "\n"\
        "/*\n"\
        "* This file has been generated by Subrepo python tool:\n"\
        "* https://github.com/DavidRbrt/subrepo\n"\
        "*/\n"\
        "\n"

    FOOTER = ""\
        "\n"\
        "#endif\n"
    # fmt: on

    def generate_line(variable, value):
        return f'#define {variable} "{value}"\n'


class Python:
    # fmt: off
    FILENAME = "version.py"

    HEADER = ""\
        '"""\n'\
        "This file has been generated by Subrepo python tool:\n"\
        "https://github.com/DavidRbrt/subrepo\n"\
        '"""\n'\
        "\n"\
        "class Version:\n"\

    FOOTER = ""
    # fmt: on

    def generate_line(variable, value):
        return f'    {variable} = "{value}"\n'


def get_version_generator(language):
    match language:
        case "c":
            return C
        case "py":
            return Python
        case _:
            return None
